# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 0.6
  - nightly
notifications:
  email: false
script:
  - travis_wait julia -e 'Pkg.clone(pwd()); Pkg.build("$pkg_name"); Pkg.test("$pkg_name"; coverage=true)'
after_success:
# build documentation
  - julia -e 'cd(Pkg.dir("RequirementVersions")); Pkg.add("Documenter"); include(joinpath("docs", "make.jl"))'
# push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("RequirementVersions")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
